const NorthCarolinaCauses =()=>{
    return [
    { title: 'The National Suicide Prevention Lifeline (Now 988)', website:'https://988lifeline.org',description: 'By dialing 988, individuals in crisis can access immediate support for suicide prevention and mental health emergencies.\n The lifeline connects individuals with trained counselors who can provide assistance and direct them to local resources.' },
    { title: 'National Alliance on Mental Illness (NAMI) Alabama', website:'https://namialabama.org', description: 'Alabama provides advocacy, education, and support for individuals living with mental health conditions and their families.\n It also offers local chapters across the state for peer support and resources.' },
    { title: 'NC Crisis Center', website:'https://www.ncdhhs.gov/divisions/mental-health-developmental-disabilities-and-substance-use-services/crisis-services', description: '' },
    { title: 'DHR NC – Division of Behavioral Health',website:'https://www.ncdhhs.gov/divisions/mhddsus', description: 'The Alabama Department of Human Resources provides mental health and behavioral health services, focusing on children, families, and individuals in need of psychological and psychiatric support.' },
    { title: 'The Alzheimer’s Association',website:'https://www.alz.org', description: 'For individuals and families affected by Alzheimer’s disease or other dementia-related conditions, the Alzheimer’s Association offers support groups, education, and resources for mental health and caregiving.' },
    { title: 'North Carolina AIDS Action Network', website:'https://southernaidscoalition.org/ella_her_project/', description: 'BAO offers behavioral health services with a focus on individuals living with HIV, providing counseling, therapy, and mental health support for marginalized populations in Alabama.' },
    { title: 'The Autism Society of Alabama',website:'https://www.autism-alabama.org', description: 'The Autism Society of Alabama provides support and resources for individuals with autism and related disorders, including mental health services, community programs, and advocacy efforts.' },
    { title: 'The National Helpline for Substance Abuse and Mental Health Services (SAMHSA)',website:'https://www.samhsa.gov/find-help', description: 'SAMHSA provides a national helpline (1-800-662-HELP) and a directory of treatment centers across the U.S., including Alabama, to help individuals find resources for addiction treatment and recovery.' },
    { title: 'DBT Self Help',website:'https://www.dbtselfhelp.com', description: 'DBTselfhelp.com is one of the most well-known resources for individuals seeking self-help materials for Dialectical Behavior Therapy.\n The website offers free worksheets, skills training resources, and detailed explanations of DBT concepts.\n It\'s a great starting point for those who want to learn and practice DBT skills on their own or supplement their therapy.' },
  ];
}
  export default NorthCarolinaCauses;