import Head from "next/head";
import Image from "next/image";
import { Box, Typography } from "@mui/material";

import PeoplePreferUs from "@/components/Home/peoplePreferUs";
import FeedbackClients from "@/components/Home/feedback";
import ServicesBox from "@/components/Home/services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kairos Integrative Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <br />
      <br />

      {/* Background Image Container */}
      <Box
        sx={{
          position: "relative",
          width: "100%",
          height: "100vh", // Full height viewport
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        {/* Optimized Responsive Image */}
        <Image
          src="/title.jpg"
          alt="Background"
          layout="fill"
          objectFit="cover"
          quality={100}
          priority
          style={{
            zIndex: -1,
          }}
        />

        {/* Overlayed Text */}
        <Typography
          variant="h3"
          sx={{
            color: "blanchedalmond",
            position: "absolute",
            textAlign: "center",
            fontWeight: "bold",
            textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
            px: 2, // Padding for better spacing on smaller screens
            fontSize: {
              xs: "1.5rem", // Smaller screens
              sm: "2rem", // Small screens
              md: "2.5rem", // Medium screens
              lg: "3rem", // Large screens
            },
          }}
        >
          Opening Late November 2024
        </Typography>
      </Box>

      {/* Other Components */}
      <ServicesBox />
      <PeoplePreferUs />
      <FeedbackClients />
    </>
  );
}
