const TermsData = [
    {Title:"Privacy of our clinic.",description:{
      title:`Integrative Behavioral Health and Medicine, Inc (“KIH,” “we,” “us,” or “our”) respects and is committed to protecting your privacy through compliance with this Privacy Policy. This Privacy Policy describes how KIH collects, uses, and shares information about you that we obtain through our website having URL https://www.kairosintegrativehealth.com.`,title:`The practices described in this Privacy Policy are not applied to protected health information (“PHI”). This Privacy Policy shall be read along with the Terms & Conditions of this Website in order to get a better understanding. Please read this policy carefully. By accessing or using our Website, you agree to this Privacy Policy.`}},
    {title:"INFORMATION YOU PROVIDE TO US",description:{
      title:`We collect the information you provide directly to us through our Website.`,title:`You choose to share your personal information with us to use our Website, request information, sign up for newsletters, make inquiries, participate in surveys or promotions, or otherwise interact with us.`,title:`Personal Information includes first and last name, e-mail address, home address, telephone number, payment card information, or date of birth, unless de-identified or encrypted.`,title:`Information collected is used to identify an individual, ensuring personalized and effective service delivery.`}},
    {title:"INFORMATION WE COLLECT",description:{
     title:`Details of visits to our Website, including traffic data, location data, logs, and other communication data, as well as information about your computer and internet connection.`,title:`Automatic data collection technologies include Cookies (small text files saved on your device for login and functionality) and Web Beacons (tiny graphic files for anonymous, non-personal usage data).`,title:`These tools help us customize the Website, enhance usability, and deliver a better user experience by analyzing traffic and preferences.`}},
    {title:"HOW IS YOUR INFORMATION USED",description:{
     title:`Deliver requested services, improve customer service, and personalize content, advertising, and communication based on your preferences.`,title:`Send promotional or critical system-related emails (with options to unsubscribe or opt out where applicable) and notify users about changes or developments to our Website or services.`,title:`Analyze data for market research, improve business operations, and offer relevant products or services while safeguarding your personal information from unauthorized use.`}},
  ]